### ISSUE TITLE
Add details about what is hacktoberfest.

### ISSUE THREAD

**Issue by Omkar-Ajnadkar** [Omkar-Ajnadkar/Intro-to-Hacktoberfest#1]

**Comment by nardsqq** [comment]
Hi, I'd love to do this 😄 . Does adding the details within the README.md suffice or do you want a separate markdown file for it?

**Comment by Omkar-Ajnadkar** [comment]
Add it to the README file only...and don't forget to add yourself to contributors...
Happy Contributing!!!🎉

**Comment by nardsqq** [comment]
Thank you Omkar! 🎉

**Comment by nardsqq** [comment]
Done! #7
